### ISSUE TITLE
bug: UDFPS and Smart pixels

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/issue_tracker#57]
### Issue type

User interface

### Device

I think that anyone who has UDFPS

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

When the "Smart Pixels" setting is enabled, UDFPS does not work well. The higher the % of pixels to be turned off, the worse the fingerprint scanner works.

### Steps to reproduce

1) EnableSmart Pixels
2) Set 75..88%
3) Trying to unlock the device with a fingerprint

### Relevant log (logcat/build log)

```shell
---
```

### Solution

The easiest way I see is to turn off "Smart pixels" while UDFPS is running, then turn it on again.

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ShevT** [comment]
Fixed - https://github.com/crdroidandroid/android_frameworks_base/commit/b4561823bbd6829d06609bd3e376e7cca472a380

**Comment by quickishfm** [comment]
This is still a problem on CrDroid 10 (guacamole/Oneplus 7 Pro).
@ShevT How can we enable the "disable_smart_pixels_on_udfps" option?

**Comment by ShevT** [comment]
> This is still a problem on CrDroid 10 (guacamole/Oneplus 7 Pro). @ShevT How can we enable the "disable_smart_pixels_on_udfps" option?

[Added...](26eca77adc3fd9cde6d48e6fd8791037aff37500)
